exports.rosterLimit = 50;
exports.memberships = [
	{
		level: 0,
		name: 'Free',
		description: 'Free minimal statkeeping features only.',
		features: [
			'Offense and defensive groupings for events',
			'Points played',
			'Touches',
			'Goals',
			'Assists',
			'Turns',
			'Blocks',
		],
		maxLines: 0,
		cost: 0,
		recurringCost: 0,
		points: true,
		touches: false,
		goals: true,
		assists: true,
		turns: true,
		blocks: true,
		yards: false,
		plusMinus: false,
		efficiency: false,
		heatmaps: false,
	},
	{
		level: 1,
		name: 'Basic',
		description:
			'Statkeeping with some advanced stats, and preset lines available',
		features: [
			'All features of Free, plus...',
			'3 preset lines per event',
			'Passing and receiving yards',
			'Plus/Minus',
			'Offensive efficiency',
			'Defensive efficiency',
		],
		maxLines: 3,
		cost: 10,
		recurringCost: 9,
		points: true,
		touches: true,
		goals: true,
		assists: true,
		turns: true,
		blocks: true,
		yards: true,
		plusMinus: true,
		efficiency: true,
		heatmaps: false,
	},
	{
		level: 2,
		name: 'Plus',
		description:
			'All features unlocked. Advanced stats with visuals, more preset lines.',
		features: [
			'All features of Free and Basic, plus...',
			'6 total preset lines per event',
			'Visual statistics, heatmaps, and graphs',
		],
		maxLines: 6,
		cost: 20,
		recurringCost: 18,
		points: true,
		touches: true,
		goals: true,
		assists: true,
		turns: true,
		blocks: true,
		yards: true,
		plusMinus: true,
		efficiency: true,
		heatmaps: true,
	},
];
